#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times

if [ -z "$1" ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

ip_address=$1

echo "PING $ip_address"
ping -c 5 "$ip_address"
