#!/usr/bin/env bash
# Configure ufw firewall to block all incoming traffic
# Except for TCP ports 22, 443 and 80.
sudo apt-get update
sudo apt-get install ufw
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw default deny incoming
sudo ufw enable
sudo ufw status
