#!/usr/bin/env bash
# This script runs the 'whoami' command under the user passed as an argument.

# Get the username from the command line argument
username="$1"
if ! id "$username" &>/dev/null; then
	sudo useradd "$username"
fi
sudo -u "$username" whoami
